### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by oScape** [m6-workshops/kata-1-300-team#2]
Florian :
- Créer le fichier txt
- Ecrire quatres phrases avec les dés

Benoit : 
- Récupérer le fichier txt
- Ecrire cinq phrases avec les dés

**Comment by fferriere** [comment]
Pour la fin de l'histoire : https://github.com/m6-workshops/kata-1-300-team/pull/3

**Comment by oScape** [comment]
J'ai presque fini le début.

**Comment by oScape** [comment]
@fferriere et @znon1 faire le review des deux pour qu'on merge. Qui est responsable des merge du repo ?

**Comment by oScape** [comment]
Duy, tu t'occupes de la 4eme ?

**Comment by znon1** [comment]
yes

**Comment by oScape** [comment]
@fferriere et @znon1 vous pouvez faire les reviews des deux premières pr ?

**Comment by znon1** [comment]
Je m'occupe de la photo ou vous avez trouvez ?

**Comment by oScape** [comment]
Non je te laisse faire. Je vais faire les merges

**Comment by fferriere** [comment]
La photo et le titre sont fait dans la PR #8
